# Workflow의 이름
name: Github Actions 실행시켜보기

# Event: 실행되는 시점을 설정
# main이라는 브랜치에 push될 때 아래 Workflow를 실행
on:
  push:
    branches:
      - main

# 하나의 Workflow는 1개 이상의 Job으로 구성
# 여러 Job은 기본적으로 병렬적으로 수행됨
jobs:
  # Job을 식별하기 위한 id
  My-Deploy-Job:
    # Job을 실행하는 Runner를 설정. ubuntu 환경/가장 최신 버전(latest)
    runs-on: ubuntu-latest

    # Step: 특정 작업을 수행하는 가장 작은 단위
    # Job은 여러 Step들로 구성되어 있다.
    steps:
      # name: step의 이름
      - name: Hello World 찍기
        # run: 명령어 쓰기(아래는 리눅스 코드)
        run: echo "Hello World"
      
      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Good"
          echo "Morning"
      
      - name: Github Actions 자체에 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
